### ISSUE TITLE
invalid arithmetic operator

### ISSUE THREAD

**Issue by devZer0** [arg7/zfs-monitor#1]
i'm getting

# iosnoop-perf -s | ./dsk-peek.sh -v /dev/sda >out &
[1] 1640645

# ./dsk-peek.sh: line 46: ((: skp = end.*512: syntax error: invalid arithmetic operator (error token is ".*512")
./dsk-peek.sh: line 54: [: : integer expression expected
./dsk-peek.sh: line 54: [: BYTES: integer expression expected

on proxmox pve 8.1.4 / debian 12 server

**Comment by devZer0** [comment]
it appears, it's being caused by the first two lines of ioperf-snoop  output, as they contain no data but header information

# iosnoop-perf -s | ./dsk-peek.sh -v /dev/sda >/dev/null
blk=end.
./dsk-peek.sh: line 51: ((: skp = end.*512: syntax error: invalid arithmetic operator (error token is ".*512")
./dsk-peek.sh: line 59: [: : integer expression expected
blk=BLOCK
./dsk-peek.sh: line 59: [: BYTES: integer expression expected

this can be fixed by 2 read commands before reading the data

# skip first 2 lines of iosnoop output, as it does not contain data
read;read
while read -r tm app pid op dsk blk sz l

**Comment by arg7** [comment]
Thanks for your input.
I've added fix, as you suggested.
