### ISSUE TITLE
WARNING: CPU:0 [LOST XXX EVENTS  spew to screen

### ISSUE THREAD

**Issue by devZer0** [arg7/zfs-monitor#2]
i would recommend  redirecting ioperf-snoop stderr output to >/dev/null, otherwise gui window would get scrambled by errors like shown in the screenshot. 

maybe stderr could be captured separately and errors being printed in the status bar at the bottom/top.

iosnoop-perf -s 2>/dev/null| ./dsk-visualize.sh /dev/sda

<img width="1430" alt="grafik" src="https://github.com/arg7/zfs-monitor/assets/3506105/dd00e214-316e-42a3-898a-46a1ff3d5bd5">

**Comment by arg7** [comment]
Thanks for debugging, I've added redirection of stderr to /dev/null, as you suggested.
